import {test} from 'node:test';
import assert from 'node:assert/strict';
import {calculate} from '../dist/calculations.js';
import {tools} from '../dist/tools.js';
import {guides,lessons} from '../dist/learning.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<=Math.max(1e-9,Math.abs(b)*1e-9),`${a} ≠ ${b}`);
const defaults=id=>Object.fromEntries(tools.find(t=>t.id===id).fields.map(f=>[f.key,f.value]));
const calc=(id,overrides={})=>calculate(id,{...defaults(id),...overrides});
test('Queda AC: FP=1 coincide com circuito resistivo',()=>near(calc('drop-ac',{system:'mono',l:10,i:10,r:20,x:10,fp:1}).values[0].value,4));
test('Queda AC: parcela capacitiva pode elevar tensão',()=>assert.ok(calc('drop-ac',{r:0,x:1,fp:.8,load:'lead'}).values[0].value<0));
test('Transformador: 100 kVA, 400 V, 5%',()=>{const o=calc('short-transformer',{s:100,v:400,z:5});near(o.values[0].value,5/Math.sqrt(3));near(o.values[2].value,.08);});
test('Adiabático: seção exata e energia limite',()=>{const o=calc('adiabatic',{i:1,t:1,k:100,s:10});near(o.values[0].value,10);near(o.values[3].value,100);assert.equal(o.warnings.length,0);assert.ok(calc('adiabatic',{i:1,t:1,k:100,s:9}).warnings.length);});
test('RLC: na ressonância, Z=R e corrente RMS=V/R',()=>{const out=calc('rlc',{r:10,l:10,c:10,f:1/(2*Math.PI*Math.sqrt(.01*.00001)),v:24});near(out.values[0].value,10);near(out.values[1].value,2.4);near(out.values[2].value,0);near(out.values[5].value,57.6);});
test('Motor: velocidade, escorregamento e balanço P=Tω',()=>{const o=calc('motor',{f:50,poles:4,n:1450,p:10});near(o.values[1].value,1500);near(o.values[2].value,100/30);near(o.values[0].value*(2*Math.PI*1450/60),10000);});
test('THD: ortogonalidade RMS e FP total',()=>{const o=calc('thd',{i1:100,i3:30,i5:0,i7:0,cos:1});near(o.values[0].value,30);near(o.values[1].value,Math.sqrt(10900));near(o.values[2].value,1/Math.sqrt(1.09));});
test('THD sem harmônicas: RMS=I1 e FP=cosφ',()=>{const o=calc('thd',{i1:10,i3:0,i5:0,i7:0,cos:.8});near(o.values[0].value,0);near(o.values[1].value,10);near(o.values[2].value,.8);});
test('Op amp: inversor distingue Av=-10 de NG=11',()=>{const o=calc('opamp');near(o.values[0].value,-2);near(o.values[1].value,-10);near(o.values[2].value,11);});
test('Op amp: não inversor e saturação',()=>{const o=calc('opamp',{type:'noninv',vin:2,high:10,low:-10});near(o.values[1].value,11);near(o.values[3].value,22);near(o.values[0].value,10);assert.equal(o.warnings.length,1);});
test('Op amp: sinal grande limitado por slew rate',()=>{const o=calc('opamp-speed',{gbw:10,ng:10,sr:Math.PI,peak:5});near(o.values[1].value,1000);near(o.values[2].value,100);near(o.values[0].value,100);});
test('Buck: duty, ripple, pico e capacitor',()=>{const o=calc('buck');near(o.values[0].value,.6);near(o.values[1].value,50);near(o.values[2].value,2.3);near(o.values[3].value,1.7);near(o.values[4].value,19.5);assert.equal(o.warnings.length,0);});
test('Boost: balanço de potência ideal e ripple',()=>{const o=calc('boost');near(o.values[0].value,2.3);near(o.values[1].value,50);near(o.values[2].value,2);near(o.values[3].value,.6);near(o.values[5].value,50);near(o.values[2].value*12,24);});
test('Conversores: aviso quando a hipótese CCM falha',()=>{assert.ok(calc('buck',{i:.1}).warnings.some(w=>w.includes('CCM')));assert.ok(calc('boost',{i:.01}).warnings.some(w=>w.includes('CCM')));});
test('Sallen-Key Butterworth: f-3dB=f0 e ganho relativo -3,0103 dB',()=>{const r=10000,c=10,k=3-Math.sqrt(2),f0=1/(2*Math.PI*r*c*1e-9),o=calc('sallen-key',{r,c,k,f:f0});near(o.values[1].value,1/Math.sqrt(2));near(o.values[2].value,f0);near(o.values[4].value,-10*Math.log10(2));});
test('Sallen-Key Q=0,5: ponto -3dB difere da frequência natural',()=>{const o=calc('sallen-key',{k:1,f:0});near(o.values[1].value,.5);near(o.values[2].value/o.values[0].value,Math.sqrt(Math.sqrt(2)-1));near(o.values[3].value,1);});
test('Térmica: Tj=105 °C e θSAmax=6 °C/W',()=>{const o=calc('thermal');near(o.values[0].value,105);near(o.values[1].value,6);near(o.values[2].value,20);assert.equal(o.warnings.length,0);});
test('Térmica: orçamento impossível e excesso geram aviso',()=>{const o=calc('thermal',{tmax:50});assert.ok(o.values[1].value<0);assert.equal(o.warnings.length,1);});
test('Guia completo para todas as 22 ferramentas',()=>{assert.equal(tools.length,22);for(const t of tools){assert.ok(guides[t.id]?.concept&&guides[t.id]?.example&&guides[t.id]?.use&&guides[t.id]?.pitfall);const out=calc(t.id);assert.ok(out.values.every(v=>Number.isFinite(v.value)));}assert.equal(lessons.length,10);for(const l of lessons){assert.ok(l.exercise&&l.answer&&l.paragraphs.length>=3);assert.ok(l.tools.every(id=>tools.some(t=>t.id===id)));}});
test('Dados inválidos e domínios físicos avançados',()=>{for(const [id,changes] of [['drop-ac',{fp:0}],['short-transformer',{z:0}],['adiabatic',{t:5.01}],['rlc',{l:0}],['motor',{poles:3}],['motor',{n:1900}],['thd',{i1:0}],['thd',{i3:-1}],['opamp',{low:10,high:0}],['opamp-speed',{ng:.5}],['buck',{out:30}],['boost',{out:10}],['sallen-key',{k:3}],['sallen-key',{k:.5}],['thermal',{ta:150,tmax:125}]])assert.throws(()=>calc(id,changes));});
